Release/v0.5.0: Case Study Integration
eclipse-tractusx/digital-product-pass pull request #12
Opened 2023-03-30 11:54 UTC by saudkhan116

# Release v0.5.0

## What is new?

### Updated
- Updated documentation
- Upgraded EDC version to 0.1.6
- Refactor passport view
- Support passport semantic version 3.0.1
- Upgraded frontend and backend integration to permanent
- Updated Exception handling and application robustness
- Updated Swagger documentation
    - Removed login/ logout auth APIs
- Updated postman collection for INT and DEV to retrieve passport version 3.0.1
- Refactor assets registration scripts for the mock provider
- Change the mock provider endpoint configuration from `/provider` to `/BPNL000000000000`
- Update all environment configuration files to adapt semantic version 3.0.1
- Upgraded frontend mockups to support semantic version 3.0.1

### Added
- Added BETA environment configuration
    - Added helm charts
    - Added backend configuration
    - Added mock provider and consumer EDC configurations
- Externalized the frontend configuration using helm charts
- Added tooltip component in frontend
- Added veracode workflow_dispatch
- Added search in backend for submodel with `idShort` as `batteryPass` in the Digital Twin Registry (DTR)
- Added `endpointAddress` parsing in backend with and without `BPN`
- Added search for `assetId` in a provider catalog using the scheme `{DigitalTwinId}-{DigitalTwinSubmodelId}`
- Enabled "OPTIONS" method in backend CORS configuration
    - Allowing local browser calls to the backend
- Support end-to-end integration with external company in BETA

### Issues Fixed
- EsLint configuration
- Veracode secret names for tractusx

### Deleted
- Removed Wrapper.js from frontend component
- Removed additional mocks in frontend configuration

2023-03-31 08:40 UTC, SebastianBezold requested changes

2023-03-31 08:40 UTC, SebastianBezold commented on consumer-backend/productpass/src/main/resources/application-beta.yml
The copyright header does not seem to be complete. SPDX Identifier for example is missing

2023-03-31 08:40 UTC, SebastianBezold commented on deployment/infrastructure/provider/init-provider.sh
> +BEARER_TOKEN='eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJIVUgzYjZrMzZvbFNQVTRDRTRaMVUxUjhVeHg4eFQwS3p4QXdLb3NkVk1VIn0.eyJleHAiOjE2Nzg4OTY3MDgsImlhdCI6MTY3ODg5NjQwOCwianRpIjoiNmU5ZDk4MjUtNDRlO
is this an actual token? please be careful with tokens that can actually be used. If this was a mistake, make sure the token cannot be used anymore and remove it from your fiel and potentially the history

2023-03-31 08:43 UTC, SebastianBezold commented
Hi @saudkhan116, beside the comments I made on the changed files, please investigate, why both Veracode and GitGuarding checks are failing and fix the related issues.

Also please let someone who is familiar with eh application review the content/feature changes.
There is a small guide in our [Developer Hub](https://eclipse-tractusx.github.io/docs/oss/code-reviews#step-1---content-review-the-responsibility-lies-with-the-product-team) section on the website

2023-03-31 09:07 UTC, matbmoser commented on consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/http/controllers/api/DataController.java
> +        if(version.equals("v3.0.1")) { // Currently supporting just version v3
The comment is wrong, the version shall match exactly the semantic version from the passport. Unfortunately at the  moment we offer support just this exact passport version. In a next releases flexible passports versions will be allowed. But thanks for the feedback 👍🏻

2023-03-31 09:35 UTC, saudkhan116 commented
Hi Sebastian, thank you for your feedback. We already investigated about veracode and gGitguardian issue.
For Gitguardian, there are no actual secrets revealed, those are just string literals (e.g., urls). Therefore the findings are false positive.
For Veracode, the secret credentials may be not defined for tractusx, they are  being printed empty and we are not able to find them. By mentioning the following keys 'secrets.VERACODE_API_ID' and 'secrets.VERACODE_API_KEY'.

2023-03-31 10:40 UTC, matbmoser commented on consumer-backend/productpass/src/main/resources/application-beta.yml
Shall I change all the headers to include the SPDX? Because now all the documents that have this SPDX missing will be changed...

2023-03-31 13:06 UTC, matbmoser approved these changes
The next PR is going to be more little, and will follow the TRG Guidelines.

This PR contains basically, the upgrade of using Battery Pass v3.0.0 to v3.0.1

I approve it from my side since we changed the mandatory things, pending to create a new PR with the headers updated 💯

2023-04-01 10:16 UTC, saudkhan116 commented on cypress.config.js
> +/**
Resolved in v0.5.1 https://github.com/eclipse-tractusx/digital-product-pass/pull/13

2023-04-03 07:28 UTC, SebastianBezold commented
Merging this with #13 in mind.

2023-04-03 07:28 UTC, merged