Release/v0.6.0.0: Redesign Battery Passport
eclipse-tractusx/digital-product-pass pull request #16
Opened 2023-04-24 14:07 UTC by matbmoser

# PR part of release v0.6.0, Sub Release v0.6.0.0

# Why we create this PR?
 
To merge the new redesign passport changes
 
# What we want to achieve with this PR?
 
Upgrade the actual design of the passport
 
# What is new?
 
- Refactor the UI according to the designs given by Accenture
- Refactor the UI 

## PR Linked to:

| Tickets |
| :---:   |
| [cmp-465](https://jira.catena-x.net/browse/CMP-465) | Redesign BatteryPassport

2023-04-27 14:35 UTC, SebastianBezold requested changes
You do have a lot of copyright header findings again. Please use your IDE capabilities. It just takes too much time for a task, that could have been automated

2023-04-27 14:35 UTC, SebastianBezold commented on src/assets/styles/components/passport/cards.scss
Copyright and License Header missing. Consider to use your IDE capabilities to auto-add them on new files

2023-04-27 14:35 UTC, SebastianBezold commented on src/assets/styles/components/passport/elementChart.scss
Copyright + License header

2023-04-27 14:35 UTC, SebastianBezold commented on src/assets/styles/components/passport/field.scss
Header again

2023-04-27 14:35 UTC, SebastianBezold commented on src/assets/styles/components/passport/passportPage.scss
Header

2023-04-27 14:35 UTC, SebastianBezold commented on src/components/passport/BarChart.vue
This license header does not seem to be complete.
At lease SPDX identifier missing. Eclipse contributors part missing

2023-04-27 14:35 UTC, SebastianBezold commented on src/components/passport/Cards.vue
Again incomplete header

2023-04-27 14:35 UTC, SebastianBezold commented on src/components/passport/ElementChart.vue
Incomplete header

2023-04-27 14:44 UTC, SebastianBezold commented
@matbmoser can you also please ask someone to do a content review, since I cannot review the CSS and JavaScript changes.
Comments about the GitGuardian findings are also appreciated if you already analyzed them

2023-04-27 18:59 UTC, matbmoser commented
> You do have a lot of copyright header findings again. Please use your IDE capabilities. It just takes too much time for a task, that could have been automated

We are aware of that... Unfortunately not all our developers have a automatic header license so we need to revise all manually and sometimes some files scape our control. They will be fixed.

2023-04-28 09:05 UTC, matbmoser commented
https://github.com/eclipse-tractusx/digital-product-pass/pull/16#issuecomment-1520229972

GitGuardian is detecting false positives in the values.yaml

2023-04-28 09:15 UTC, matbmoser commented
https://github.com/eclipse-tractusx/digital-product-pass/pull/16#issuecomment-1527244768

@SebastianBezold I will ask the question today in the DevSecOps meeting, I have it configured in Intelij however mostly we use VSCode and the structure provided limits us (because it does not includes the SPDX field and the header notice at the same time)

2023-04-28 09:34 UTC, matbmoser commented
@SebastianBezold I just created a discussion about that in the tractus-x dev mailing list, so we can find the best practices in this case.

2023-04-28 15:22 UTC, matbmoser commented
@SebastianBezold we solved the necessary fixes for the license headers in the last PR from the version v0.6.0 -> #24
Please review the PR and let us know your feedback.

2023-04-28 15:25 UTC, saudkhan116 commented
Hi @SebastianBezold, I have reviewed the JavaScript and CSS content and they are fine enough.

2023-05-03 15:18 UTC, matbmoser commented
Sub release strategy (slit bigger releases) proposed by the System Team failed to work, because of lack of tracking and the lack of rebase possibilities. https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow


The new commit strategy will follow this diagram from gitflow:

![image](https://user-images.githubusercontent.com/71728767/235960923-93ee97e3-b30b-4f0c-90e7-9a01017a0ac8.png)



Only one PR will be merged, the #24

2023-05-03 15:31 UTC, SebastianBezold commented
Merging without copyright headers, but tracking in #24

2023-05-03 15:31 UTC, merged