Chore/adapt models frontend: Support new models from BatteryPass, DigitalProductPass and TransmissionPass
eclipse-tractusx/digital-product-pass pull request #336
Opened 2024-06-19 14:31 UTC by saudkhan116

# Why we create this PR?
 
Adapt Frontend componet with the following new models:

- Digital Product Pass v5.0.0
- Battery Pass 6.0.0
- Transmission Pass 3.0.0

# What we want to achieve with this PR?
 
To support new model versions in the dpp-frontend
 
# What is new?
 
## Updated
- Updated frontend component to support new data model versions:
    - Digital Product Pass v5.0.0
    - Battery Pass 6.0.0
    - Transmission Pass 3.0.0

## PR Linked to:
#270

2024-06-19 14:54 UTC, matbmoser approved these changes

2024-06-19 14:54 UTC, matbmoser commented on dpp-frontend/package.json
>      "vue-router": "^4.0.13",
IP Checks needs to be runned here!

2024-06-19 14:54 UTC, matbmoser commented on dpp-backend/scripts/requirements.txt
> +requests==2.31.0
We need Ip check here

2024-06-19 15:00 UTC, matbmoser commented on dpp-backend/scripts/requirements.txt
> +requests==2.31.0
[DEPENDENCIES_BACKEND_SCRIPTS.txt](https://github.com/user-attachments/files/15902785/DEPENDENCIES_BACKEND_SCRIPTS.txt)

2024-06-19 15:00 UTC, matbmoser commented on dpp-backend/scripts/requirements.txt
> +requests==2.31.0
you can use it and remove the txt

2024-06-19 15:04 UTC, matbmoser requested changes
Click the wrong button, IP checks needed

2024-06-20 12:08 UTC, saudkhan116 commented on dpp-frontend/package.json
>      "vue-router": "^4.0.13",
IP checks executed

2024-06-20 14:00 UTC, matbmoser approved these changes
Approved!

2024-06-20 14:09 UTC, merged