Feature/simple wallet: DPP Verification Simple Wallet Component
eclipse-tractusx/digital-product-pass pull request #343
Opened 2024-06-21 17:17 UTC by matbmoser

# Why we create this PR?
 
For executing the PoC of this feature https://github.com/eclipse-tractusx/sig-release/issues/655, it was needed a simple wallet that is able to sign credentials and verify them too. It should manage the credentials.
 
# What we want to achieve with this PR?
 
Have a simple wallet that can:
- Sign Credentials
- Generate JSONLD Contexts for SAMM Json Schemas
- Verify Credentials
- Manage Private and Public Keys
- Enable DID web methods
- Manage authentication and authorization
- Store the credentials
- Be decentral
 
# What is new?
 
## Added
- Added the simple wallet component built in python
- Added functionality to issue certified data credentials or any verifiable credential with datamodel v2
- Added functionality to verify credentials with JsonWebSignature2020
- Added DID method to visualize the public key
- Added api translator from SAMM json schema to JSON-LD Context
- Added bpn authorization mechanism with api keys
- Added storage of credentials
- Added private and public key managers.

## PR Linked to:
 https://github.com/eclipse-tractusx/sig-release/issues/655

2024-06-21 17:19 UTC, matbmoser commented
I dont know why it removed this parts License and Security, I will re-add it

2024-06-21 17:33 UTC, matbmoser commented
All the code was done by me and worked by me before here: https://github.com/matbmoser/simple-wallet and now in Tractus-X. So no IP checks are needed

2024-06-28 14:18 UTC, saudkhan116 requested changes

2024-06-28 14:18 UTC, saudkhan116 commented on .github/workflows/publish-dpp-verification-wallet-docker-image.yml
> +    if: github.repository == 'eclipse-tractusx/digital-product-pass'
remove the checks

2024-06-28 14:18 UTC, saudkhan116 commented on .github/workflows/publish-dpp-verification-wallet-docker-image.yml
> +  build-on-ghcr:
remove this block of ghcr, it is no more used and should not be referenced anywhere

2024-06-28 14:18 UTC, saudkhan116 commented on .github/workflows/publish-dpp-verification-wallet-docker-image.yml
> +    if: github.repository != 'eclipse-tractusx/digital-product-pass'
remove the check

2024-06-28 14:18 UTC, saudkhan116 commented on charts/digital-product-pass/templates/ingress-backend.yaml
> -  # Copyright (c) 2022, 2024 BMW AG, Henkel AG & Co. KGaA
There should be only year of creation in the license headers. BMW and Henkel should be in two different lines.
The updated license header should look like this:

Copyright (c) 2022 BMW AG,
Copyright (c) 2022 Henkel AG & Co. KGaA
Copyright (c) 2023 CGI Deutschland B.V. & Co. KG

2024-06-28 14:18 UTC, saudkhan116 commented on dpp-backend/scripts/logging.ini
> -Copyright (c) 2023, 2024 CGI Deutschland B.V. & Co. KG
same as above

2024-06-28 14:18 UTC, saudkhan116 commented on charts/digital-product-pass/templates/ingress-backend.yaml
>  # Copyright (c) 2023, 2024 CGI Deutschland B.V. & Co. KG
see above

2024-06-28 14:18 UTC, saudkhan116 commented on dpp-verification/charts/simple-wallet/LICENSE
> +   Copyright 2023, 2024 CGI Deutschland B.V. & Co. KG
The licenses look different here and in copyright headers, please check.

2024-06-28 14:18 UTC, saudkhan116 commented on dpp-verification/charts/simple-wallet/templates/configmap.yaml
> +# Copyright (c) 2022, 2024 BMW AG, Henkel AG & Co. KGaA
see above

2024-06-28 14:24 UTC, matbmoser commented on .github/workflows/publish-dpp-verification-wallet-docker-image.yml
> +    branches: [ "main", "develop", "feature/simple-wallet" ]
Good

2024-06-28 14:24 UTC, matbmoser commented on .github/workflows/publish-dpp-verification-wallet-docker-image.yml
> +  REGISTRY: 'ghcr.io'
ok

2024-06-28 14:27 UTC, matbmoser commented
Ok solve the workflow things you told me 
Question the ingress things are not going to be solved when merged?
Maybe we need to merge main on this branch so it gets the latest changes.

2024-06-28 14:32 UTC, matbmoser commented
Ok @saudkhan116 I removed the ingress change so in the latest version with the ingress fixed there will be what you have already done.

2024-06-28 16:01 UTC, saudkhan116 requested changes
The license headers are still not yet correct as agreed

2024-07-01 14:24 UTC, saudkhan116 commented
@matbmoser, as per our discussion, we are now aligned and agreed on the copyright license headers. We will still use date range (creation date and the last updated date) to a changed file. Secondly, we make a separate copyright line for each company/code owner where applicable.

Example:

# Copyright (c) 2022, 2024 BMW AG
# Copyright (c) 2022, 2024 Henkel AG & Co. KGaA
# Copyright (c) 2023, 2024 CGI Deutschland B.V. & Co. KG
# Copyright (c) 2023, 2024 Contributors to the Eclipse Foundation
 ...
 
DPP-verification:
# Copyright (c) 2023, 2024 BMW AG
# Copyright (c) 2023, 2024 CGI Deutschland B.V. & Co. KG
# Copyright (c) 2024 Contributors to the Eclipse Foundation
...

2024-07-01 15:27 UTC, saudkhan116 approved these changes

2024-07-01 15:27 UTC, saudkhan116 commented on dpp-verification/charts/simple-wallet/LICENSE
> +   Copyright 2023, 2024 CGI Deutschland B.V. & Co. KG
Ultimately, we need to change license headers in all files. This change will be followed there

2024-07-03 06:34 UTC, matbmoser commented
There was a bug in the "expiration date" check. Now its fixed

2024-07-03 08:29 UTC, matbmoser commented
I needed to fix the chart version

2024-07-03 08:31 UTC, merged