chore(deps): updated spring-boot dependencies
eclipse-tractusx/digital-product-pass pull request #357
Opened 2024-07-04 12:41 UTC by saudkhan116

# Why we create this PR?
 
- Updated spring boot dependencies, reported by dependabot. 
 
# What is new?
 ## Updated
- Updated spring boot dependencies, reported by dependabot. 

## PR Linked to:

https://github.com/eclipse-tractusx/digital-product-pass/pull/347
https://github.com/eclipse-tractusx/digital-product-pass/pull/339
https://github.com/eclipse-tractusx/digital-product-pass/pull/329
https://github.com/eclipse-tractusx/digital-product-pass/pull/219

2024-07-04 14:19 UTC, matbmoser approved these changes

2024-07-08 11:30 UTC, matbmoser approved these changes

2024-07-08 11:32 UTC, matbmoser requested changes
Please check for the dependencies if they need to be refreshed again. There is one change shown...
![image](https://github.com/eclipse-tractusx/digital-product-pass/assets/71728767/9c5db13a-3da0-444e-99ce-68d974fb6a14)

This other dependency file also needs to be updated

2024-07-08 11:47 UTC, saudkhan116 commented
> Please check for the dependencies if they need to be refreshed again. There is one change shown... ![image](https://private-user-images.githubusercontent.com/71728767/346542308-9c5db13a-3da0-444e-99ce-68d974fb6a14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mzk1MzUsIm5iZiI6MTcyMDQzOTIzNSwicGF0aCI6Ii83MTcyODc2Ny8zNDY1NDIzMDgtOWM1ZGIxM2EtM2RhMC00NDRlLTk5Y2UtNjhkOTc0ZmI2YTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDExNDcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3YmMwYmZhMTRmZWE0NDJhNDUyYjllZDBmMDJiNmUzMDIwYjU3YjlkNGQyZGZkNGI5MTlhZDJlN2U1OWYxZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pDOX1GwngymQo6ug8UREGWL56wlCZKU4fGWLYj9U8hU)
> 
> This other dependency file also needs to be removed

Issue fixed, please check.

2024-07-11 12:42 UTC, matbmoser approved these changes

2024-07-11 16:10 UTC, merged