Chore/frontend bug fix
eclipse-tractusx/digital-product-pass pull request #376
Opened 2024-07-11 15:15 UTC by saudkhan116

# Why we create this PR?
 
<< Quick description why the PR is being opened >>
 
# What we want to achieve with this PR?
 
<< Quick description of the objective of the PR >>
 
# What is new?
 
<< Content of the version change log functionalities OR functionalities >>

## PR Linked to:

<< If there is a ticket include it here >>

2024-07-12 11:10 UTC, matbmoser approved these changes

2024-07-19 09:02 UTC, matbmoser approved these changes
Approved (add the ip checks)

2024-07-19 15:34 UTC, matbmoser requested changes
IP CHECKS ARE NEEDED

2024-07-19 15:52 UTC, matbmoser approved these changes

2024-07-19 16:22 UTC, saudkhan116 commented
IP checked executed, no IP issues found!

2024-07-19 16:22 UTC, merged