Added the Explorer Path to the DPP-Verification tutorial for the Tractus-X Community Days
eclipse-tractusx/digital-product-pass pull request #457
Opened 2024-11-29 08:17 UTC by ELebedkin

# Why we create this PR?
 
This PR is necessary to provide the latest version of the showcase demo for the Tractus-X Community Days taking place on December 5th and 6th.

# What we want to achieve with this PR?

The goal of this PR is to offer a suitable, non-technical approach that allows business users, experts, and innovation enthusiasts to easily try out the DPP verification process.
 
# What is new?
 
- Introduced a new tutorial path called "Explorer Path" (explorer-path-insomnia).
- Added a data payload link for downloading the Insomnia API calls.
- Improved the overall process with a smoother and more non-technical explanation of the steps involved.

## PR Linked to:

-

2024-12-01 22:47 UTC, matbmoser commented
Please pull the changes from main, I updated our dependency files and workflows

2024-12-01 22:48 UTC, matbmoser requested changes
For every image we need to add a .license. In general looks really good, we could merge once it's there. Please make sure that the files do not contain spaces, this can bring problems for different OS.

2024-12-02 13:47 UTC, ELebedkin commented
@matbmoser I have pulled the changes, added to every image in the tutorial an additional license file - as you have mentioned it - and improved the whole process (explorer + builders path) and completed it. so there is no separate aspect-model.md or digital-twin.md, they are now a part of the explorer and builders path, which are at the end linking back to the readme.md file step 3 generating a qr-code. 

Due to the confussion with the many commits: i swapped test and main branch. 
It should now be up2date.

2024-12-02 17:53 UTC, matbmoser requested changes

2024-12-02 17:53 UTC, matbmoser commented on dpp-tutorial/resources/screenshots/generate_licenses_python_script/generate_licenses.py
> +print("All old license files deleted and new license files generated!")
Please do not commit this!

Also use the following license template:

```
## NOTICE

This work is licensed under the [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/legalcode).

- SPDX-License-Identifier: CC-BY-4.0
- SPDX-FileCopyrightText: 2023, 2024 BMW AG
- SPDX-FileCopyrightText: 2023, 2024 CGI Deutschland B.V. & Co. KG
- SPDX-FileCopyrightText: 2024 Contributors to the Eclipse Foundation
- Source URL: https://github.com/eclipse-tractusx/digital-product-pass

```

2024-12-02 17:53 UTC, matbmoser commented on dpp-tutorial/resources/screenshots/agreebutton.png.license
> +- Source URL: https://github.com/eclipse-tractusx/digital-product-pass
Please use this template:

```md
## NOTICE

This work is licensed under the [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/legalcode).

- SPDX-License-Identifier: CC-BY-4.0
- SPDX-FileCopyrightText: 2023, 2024 BMW AG
- SPDX-FileCopyrightText: 2023, 2024 CGI Deutschland B.V. & Co. KG
- SPDX-FileCopyrightText: 2024 Contributors to the Eclipse Foundation
- Source URL: https://github.com/eclipse-tractusx/digital-product-pass

```

2024-12-02 17:54 UTC, matbmoser requested changes
Try to pack everything in some commits 88 is much for the fewer changes you made

2024-12-04 13:30 UTC, matbmoser commented on dpp-tutorial/explorer-path.md
> +> [!Tip]
```suggestion
> [!TIP]
```

2024-12-04 13:30 UTC, matbmoser commented on dpp-tutorial/explorer-path.md
> +> [!Note]
```suggestion
> [!NOTE]
```

2024-12-04 13:31 UTC, matbmoser commented on dpp-tutorial/explorer-path.md
> +> [!Note]
```suggestion
> [!NOTE]
```

2024-12-04 13:31 UTC, matbmoser commented on dpp-tutorial/explorer-path.md
> +> [!Caution]
```suggestion
> [!CAUTION]
```

2024-12-04 13:31 UTC, matbmoser commented on dpp-tutorial/explorer-path.md
> +> [!Note]
```suggestion
> [!NOTE]
```

2024-12-04 13:31 UTC, matbmoser commented on dpp-tutorial/explorer-path.md
> +> [!Important]
```suggestion
> [!IMPORTANT]
```

2024-12-04 13:33 UTC, matbmoser requested changes
Please change this to uppercase :)
But wonderful job! 🚀

2024-12-04 13:33 UTC, matbmoser commented on dpp-tutorial/explorer-path.md
> +> [!Important]
```suggestion
> [!IMPORTANT]
```

2024-12-04 13:33 UTC, matbmoser commented on dpp-tutorial/explorer-path.md
> +> [!Note]
```suggestion
> [!NOTE]  
```

2024-12-04 13:33 UTC, matbmoser commented on dpp-tutorial/explorer-path.md
> +> [!Note]
```suggestion
> [!NOTE]  
```

2024-12-04 13:33 UTC, matbmoser commented on dpp-tutorial/builder-path.md
> +> [!Note]
```suggestion
> [!NOTE]  
```

2024-12-04 13:33 UTC, matbmoser commented on dpp-tutorial/builder-path.md
> +> [!Caution]
```suggestion
> [!CAUTION]
```

2024-12-04 13:33 UTC, matbmoser commented on dpp-tutorial/builder-path.md
> +> [!Note]
```suggestion
> [!NOTE]
```

2024-12-04 13:35 UTC, matbmoser approved these changes
LGTM, let merge this! Wonderful job @ELebedkin

2024-12-04 13:39 UTC, merged